## ---------- Script -----------------
##
## Script name: 
##
## Purpose of script: Generate tappAS input (expression matrix and phenotype file) for aggregated RNA-Seq dataset 
##
## Author: Szi Kay Leung
##
## Email: S.K.Leung@exeter.ac.uk
##
## ---------- Notes -----------------
##
## Aggregated RNA-Seq dataset = ADBDR (core 96 samples) + Mayp + RosMAP dataset
## Expression file generated for each dataset from kallisto alignment of RNA-Seq dataset to Iso-Seq scaffold  
## Phenotype file generated by extracting Case/Control status from meta files
## 

## ---------- Packages -----------------

suppressMessages(library(dplyr))


## ---------- Directory  -----------------

WKD_DIR = "/lustre/projects/Research_Project-MRC148213/lsl693/AD_BDR/"
TAPPAS_INPUT_DIR = paste0(WKD_DIR, "TAPPAS_INPUT/Large_RNASeq_Expression/")

Expression_input <- list(
  Rosmap = read.table(paste0(WKD_DIR, "Differential/C_Hybrid_Public/Rosmap/1_aligned/AllBDRTargeted_Rosmap_RNASeq.expression.txt")), 
  Mayo = read.table(paste0(WKD_DIR, "Differential/C_Hybrid_Public/Mayo/1_aligned/AllBDRTargeted_Mayo_RNASeq.expression.txt")),
  BDR = read.table(paste0(WKD_DIR, "Differential/B_Hybrid_96/AllBDRTargeted_RNASeq.expression.txt"))
)

Phenotype_input <- list(
  BDR = read.table(paste0(WKD_DIR, "0_metadata/A_IsoSeq/Tappas/ADBDR_MinusIntermediate_RNASeqPhenotypeTAPPAS.txt"), header = T),
  Rosmap = read.csv(paste0(WKD_DIR, "Differential/C_Hybrid_Public/Rosmap/0_metadata/synapseid_phenotype.csv")),
  Mayo = read.csv(paste0(WKD_DIR, "Differential/C_Hybrid_Public/Mayo/0_metadata/MayoRNAseq_final_metadata.csv"))
)

cat("Number of samples in BDR dataset:", ncol(Expression_input$BDR), "\n")
cat("Number of samples in ROSMAP dataset:", ncol(Expression_input$Rosmap), "\n")
cat("Number of samples in Mayo dataset:", ncol(Expression_input$Mayo), "\n")
cat("Total samples:", ncol(Expression_input$Rosmap) + ncol(Expression_input$Mayo) + ncol(Expression_input$BDR))


## ---------- Prepare Expression file  -----------------

# Merge all the expression input files to create one big expression matrix
Merged_Expression <- merge(merge(Expression_input$Rosmap, Expression_input$Mayo, by.x = 0, by.y = 0),
      ADBDR, by.x = "Row.names", by.y = 0) %>% tibble::column_to_rownames(., var = "Row.names")


## ---------- Prepare Phenotype file  -----------------

Phenotype_output <- list()

# Create a tappAS phenotype file for Mayo dataset with column names matching expression file 
Phenotype_output$Mayo <- Phenotype_input$Mayo %>% filter(paste0("X", individualID) %in% colnames(Expression_input$Mayo)) %>% 
  select(individualID,Braak) %>% 
  mutate(group = ifelse(Braak < 3 , "CONTROL","CASE"),
         sample = paste0("X",individualID)) %>%
  select(sample,group)

# Create a tappAS phenotype file for Rosmap dataset with column names matching expression file 
Phenotype_output$ROSMAP <- Phenotype_input$Rosmap %>% filter(paste0("X", specimenID) %in% colnames(Expression_input$Rosmap)) %>%
  select(specimenID,braaksc) %>% 
  mutate(group = ifelse(braaksc < 3 , "CONTROL","CASE"),
         sample = paste0("X",specimenID)) %>%
  select(sample,group)

# Merge all the phenotype files to create one phenotype file
Merged_Phenotype <- rbind(Phenotype_input$BDR, Phenotype_output$Mayo, Phenotype_output$ROSMAP)
Merged_Phenotype <- Merged_Phenotype %>% arrange(desc(group))


## ---------- Generate output files  -----------------

write.table(Merged_Phenotype, paste0(TAPPAS_INPUT_DIR,"/LargeRNASeq_PhenotypeTAPPAS.txt"), quote = F, row.names = F, sep = "\t")
write.table(Merged_Expression, paste0(TAPPAS_INPUT_DIR,"/LargeRNASeq_Expression.txt"), quote = F, sep = "\t")
